user_id=c(111,112,113,114,115)
user_name=c("Ayesha","Rehaan","Samiksha","Chaithanya","Asra")
user=data.frame("ID"=user_id,"Name"=user_name)
user$user_location=c("Belur","Banglore","Raichur","Bidar","Kolar")
str(user)
summary(user)
user$Name
user$ID
user$user_name
user
user[1]
user[["Name"]]
user$ID
dim(user)
user=rbind(user,c(5,"Ayera"))
user=cbind(user,"Company"=c("Wipro","Infosys","Google","TCS","Toshiba"))
user=user[-c(1),]
user
length(user)
user=user[,-c(1)]
